CREATE TABLE IF NOT EXISTS `#__ingest_dspace` (
    `id` INTEGER COMMENT 'The id generated by DSpace when ingested.',
    `harvest_id` INTEGER COMMENT 'The id of the harvest used to retrieve this item.',
    `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    PRIMARY KEY (`id`, `harvest_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
